create table if not exists presentations (id uuid primary key default gen_random_uuid(), user_id uuid, title text not null, audience text, purpose text, tone text, slide_count int default 8, theme_id uuid, created_at timestamptz not null default now());
create table if not exists slides (id uuid primary key default gen_random_uuid(), presentation_id uuid references presentations(id) on delete cascade, order_index int not null default 0, layout_type text default 'title_bullets', heading text, bullets text[], notes text, created_at timestamptz not null default now());
create table if not exists themes (id uuid primary key default gen_random_uuid(), user_id uuid, name text not null, font text not null, primary_colour text not null, secondary_colour text not null, accent_colour text not null, layout_template text default 'title_bullets', created_at timestamptz not null default now());
create table if not exists content_drafts (id uuid primary key default gen_random_uuid(), slide_id uuid references slides(id) on delete cascade, value jsonb, source text, confidence numeric, review_status text default 'unreviewed', created_at timestamptz not null default now());

alter table presentations enable row level security;
alter table slides enable row level security;
alter table themes enable row level security;
alter table content_drafts enable row level security;

drop policy if exists "presentations_v1_read" on presentations; create policy "presentations_v1_read" on presentations for select using (true);
drop policy if exists "presentations_v1_write" on presentations; create policy "presentations_v1_write" on presentations for all using (true) with check (true);
drop policy if exists "slides_v1_read" on slides; create policy "slides_v1_read" on slides for select using (true);
drop policy if exists "slides_v1_write" on slides; create policy "slides_v1_write" on slides for all using (true) with check (true);
drop policy if exists "themes_v1_read" on themes; create policy "themes_v1_read" on themes for select using (true);
drop policy if exists "themes_v1_write" on themes; create policy "themes_v1_write" on themes for all using (true) with check (true);
drop policy if exists "content_drafts_v1_read" on content_drafts; create policy "content_drafts_v1_read" on content_drafts for select using (true);
drop policy if exists "content_drafts_v1_write" on content_drafts; create policy "content_drafts_v1_write" on content_drafts for all using (true) with check (true);

insert into themes (name, font, primary_colour, secondary_colour, accent_colour) values ('Corporate Bold', 'Inter', '#1a1a2e', '#16213e', '#0f3460'), ('Clean Education', 'Lato', '#2c3e50', '#ecf0f1', '#3498db'), ('Warm Coach', 'Poppins', '#2d3436', '#dfe6e9', '#e17055'), ('Minimal Executive', 'Roboto', '#212121', '#f5f5f5', '#424242') on conflict do nothing;

insert into presentations (title, audience, purpose, tone, slide_count, theme_id) values ('Q3 Investor Pitch', 'Investors', 'Fundraise', 'persuasive', 6, (select id from themes where name='Corporate Bold')), ('Intro to Photosynthesis', 'High school students', 'Teach concept', 'educational', 8, (select id from themes where name='Clean Education')), ('Sales Enablement Workshop', 'Sales team', 'Train', 'motivational', 5, (select id from themes where name='Warm Coach')) on conflict do nothing;

insert into slides (presentation_id, order_index, heading, bullets, notes) values ((select id from presentations where title='Q3 Investor Pitch'), 0, 'The Opportunity', array['$50B TAM', '12% annual growth', 'Underserved mid-market'], 'Open with market size to frame urgency.'), ((select id from presentations where title='Q3 Investor Pitch'), 1, 'Our Solution', array['AI-powered platform', '10x faster than manual', 'Proven in 3 pilots'], 'Show the product, not the vision.'), ((select id from presentations where title='Q3 Investor Pitch'), 2, 'Traction', array['$2M ARR', '150% net retention', '40 enterprise clients'], 'Numbers speak louder than slides.'), ((select id from presentations where title='Intro to Photosynthesis'), 0, 'What is Photosynthesis?', array['Plants make food from sunlight', 'Uses CO2 and water', 'Produces oxygen'], 'Start with a simple definition.'), ((select id from presentations where title='Intro to Photosynthesis'), 1, 'The Process', array['Light absorbed by chlorophyll', 'Water split into hydrogen and oxygen', 'CO2 converted to glucose'], 'Walk through each step slowly.'), ((select id from presentations where title='Sales Enablement Workshop'), 0, 'Why We''re Here', array['Align on Q3 targets', 'Share new playbook', 'Practice objection handling'], 'Set the tone: this is hands-on.') on conflict do nothing;